version: "3"
services:
  db:
    container_name: PostgresSQl
    image: postgres:14.2
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    container_name: 'web_app'
    restart: always
    env_file:
      - .env
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./flask_project:/flask_project
    links:
      - db
    ports:
      - "8000:8000"

  nginx:
    container_name: Nginx
    restart: always
    build:
      context: nginx/
      dockerfile: Dockerfile
    links:
      - web
    ports:
      - "80:80"
volumes:
  pgdata: