version: "3"
services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6.8
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  web:
    container_name: 'web_app'
    command:
      bash -c "python3 /flask_project/manage.py"
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PY_AUTORELOAD: true
        - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./flask_project:/flask_project
    links:
      - db
    ports:
      - "8000:8000"

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    links:
      - web
    ports:
      - "80:80"
volumes:
  pgdata:
  pgadmin-data: