"""Initial migration.

Revision ID: 9307173bb159
Revises: 
Create Date: 2022-06-19 12:23:58.219193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9307173bb159'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'director', ['id'])
    op.create_unique_constraint(None, 'film', ['id'])
    op.create_unique_constraint(None, 'genre', ['id'])
    op.create_unique_constraint(None, 'role', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'genre', type_='unique')
    op.drop_constraint(None, 'film', type_='unique')
    op.drop_constraint(None, 'director', type_='unique')
    # ### end Alembic commands ###
